backend:
  name: git-gateway
  branch: develop

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'planet'
    label: 'Planet'
    format: 'frontmatter'
    folder: 'content/planets'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Alternate Title', name: 'altTitle', widget: 'string' }
      - { label: 'Planet Image', name: 'planetImage', widget: 'image' }
      - { label: 'Planet Lead-In Text', name: 'leadIn', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
